---
id: 315
title: Try
---

## Try
We've just talked about throwing exceptions. 
It might be very confusing to understand, why would you throw these strange exceptions,
if you could just simply log an error message and return.
The whole thing is that actually, we can catch these exceptions using the `try-catch` block:

```panda
Int by = 0 // user data

try {
    if (by == 0) {
        throw new Exception('Cannot divide by zero') // throw error
    }

    log 100/by
} 
catch (Exception e) {
    log e.getMessage() // print message of the caught exception
}
```

Using this `try-catch` you can also catch exceptions thrown in Java sources.